FROM java:8

RUN mkdir /opt/dynamodb
ADD https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz /opt/dynamodb/dynamodb.tar.gz

WORKDIR /opt/dynamodb
RUN tar xzf dynamodb.tar.gz

CMD java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
