FROM python:2.7

RUN mkdir /root/SteamyReviews
WORKDIR /root/SteamyReviews

ADD requirements.txt .
RUN pip install -r requirements.txt
RUN python -c "import nltk; nltk.download('punkt')"

EXPOSE 5000 8000

CMD gunicorn -w 4 app:app
